###
POST http://40.122.147.73:6000/firebase/notification
content-type: application/json

{
    "message" : "HEY",
    "registrationToken" : "f3LkenFZ_xY:APA91bE-cOJTIbBgCqOAHABGeefYYTizhtSU3CIA3Tw46FbQJXf53j4muHk4QP_M4cBnUkNpx75lyVx4UvBZ3aJr9pLLeYDOZeFIAPwAEe77z-xRFulpLjxAzPME86uC49F8zlIeyl8U"
}

###
POST http://40.122.147.73:6000/hey
content-type: application/json

{
    "message" : "HEY"
}

