######################################################################
#################         GET ALL USERS        #######################
######################################################################
GET http://40.117.186.20:3000/users/all


######################################################################
#################   POPULATE DB WITH USERS     #######################
######################################################################

POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "John Albert", "password" : "password1"}
##################################################################### 
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Mary Monroe", "password" : "password2"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Aryan Sharma", "password" : "password3"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "John Wastson", "password" : "password4"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Tim Paine", "password" : "password5"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Leslie Major", "password" : "password6"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Albert Nosetien", "password" : "password7"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Mohammad Ali", "password" : "password8"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Ali Zayed", "password" : "password9"}
#####################################################################
POST http://40.117.186.20:3000/users/register
Content-Type: application/json 

{ "name" : "Justin Jackson", "password" : "password10"}
#####################################################################

######################################################################
#################      TEST THE API CALLS      #######################
######################################################################
POST http://40.117.186.20:3000/users/login
Content-Type: application/json

{ "BadRequest" : "BadRequest"}
######################################################################
POST http://40.117.186.20:3000/users/login
Content-Type: application/json

{ "name" : "wrong_username", "password" : "password1"}
######################################################################
POST http://40.117.186.20:3000/users/login
Content-Type: application/json

{ "name" : "user1", "password" : "wrong_password"}
######################################################################
POST http://40.117.186.20:3000/users/login
Content-Type: application/json

{ "name" : "user1", "password" : "password1"}
######################################################################
