######################################################################
#################      GET ALL ACTIVITIES     ########################
######################################################################
GET http://40.117.186.20:3000/activities/all

######################################################################
##################  POPULATE DB WITH ACTIVITIES  #####################
######################################################################
POST http://40.117.186.20:3000/activities/add
Content-Type: application/json

{ "aid" : "Sparkling Knights", "name" : "Cpen221 Exam Prep", "leader" : "John Albert", "usernames" : ["John Albert"], "major" : "CPEN", "course" : ["CPEN221"], "school" : "UBC", "lat" : "49.264708", "long" : "-123.238712", "status" : "1",
    "info" : "Preparing for CPEN221 Exam 2020W Term1" }
#####################################################################
POST http://40.117.186.20:3000/activities/add
Content-Type: application/json

{ "aid" : "Latvian Cucumbers", "name" : "OS161 and Chill", "leader" : "Aryan Sharma", "usernames" : ["Aryan Sharma"], "major" : "ELEC", "course" : ["CPEN331"], "school" : "UBC", "lat" : "49.237816", "long" : "-123.157516", "status" : "1",
    "info" : "Crying and debuggind session every day:)" }
#####################################################################
POST http://40.117.186.20:3000/activities/add
Content-Type: application/json

{ "aid" : "Australian Oranges", "name" : "System Architecture Interviews", "leader" : "Tim Paine", "usernames" : ["Tim Paine"], "major" : "CPSC", "course" : ["CPEN411"], "school" : "UBC", "lat" : "49.286659", "long" : "-123.137947", "status" : "1",
    "info" : "Job Interview Practice Sessions with CPEN411 Alumni" }
#####################################################################
POST http://40.117.186.20:3000/activities/add
Content-Type: application/json

{ "aid" : "Fruit Party", "name" : "400A Research Group", "leader" : "Albert Nosetien", "usernames" : ["Albert Nosetien"], "major" : "IGEN", "course" : ["CPEN400A"], "school" : "UBC", "lat" : "49.248911", "long" : "-123.029285", "status" : "1",
    "info" : "Meeting and discussing Modern Web Application Security DrawBacks" }
#####################################################################
POST http://40.117.186.20:3000/activities/add
Content-Type: application/json

{ "aid" : "Very Easy Id", "name" : "Cpen412 Lab Group 2", "leader" : "Ali Zayed", "usernames" : ["Ali Zayed"], "major" : "MECH", "course" : ["CPEN411", "CPEN412" , "CPEN421"], "school" : "UBC", "lat" : "49.313525", "long" : "-123.142238", "status" : "1",
    "info" : "Meet and Discuss CPEN412 Labs with TA" }
#####################################################################

######################################################################
#################       JOIN AN ACTIVITY       #######################
######################################################################
POST http://40.117.186.20:3000/activities/joinupdate
Content-Type: application/json

{ "username" : "Mary Monroe", "aid" : "Sparkling Knights" }
######################################################################
POST http://40.117.186.20:3000/activities/joinupdate
Content-Type: application/json

{ "username" : "John Watson", "aid" : "Latvian Cucumbers" }
######################################################################
POST http://40.117.186.20:3000/activities/joinupdate
Content-Type: application/json

{ "username" : "Leslie Major", "aid" : "Australian Oranges" }
######################################################################
POST http://40.117.186.20:3000/activities/joinupdate
Content-Type: application/json

{ "username" : "Mohammad Ali", "aid" : "Fruit Party" }
######################################################################
POST http://40.117.186.20:3000/activities/joinupdate
Content-Type: application/json

{ "username" : "Justin Jackson", "aid" : "Very Easy Id" }
######################################################################

POST http://40.117.186.20:3000/activities/leaveupdate
Content-Type: application/json

{ "username" : "Aryan Sharma", "aid" : "Latvian Cucumbers" }