######################################################################
#################       GET ALL PROFILES      ########################
######################################################################
GET http://40.117.186.20:3000/profiles/all

######################################################################
################   POPULATE DB WITH PROFILES   #######################
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "John Albert", "name" : "John", "major" : "CPEN", "school" : "UBC", "phone" : "123-456-7890", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN221"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Mary Monroe", "name" : "Mary", "major" : "CPEN", "school" : "UBC", "phone" : "234-567-8901", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN221", "CPEN211"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Aryan Sharma", "name" : "Aryan", "major" : "ELEC", "school" : "UBC", "phone" : "345-678-9012", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN331"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "John Watson", "name" : "Watson", "major" : "ELEC", "school" : "UBC", "phone" : "456-789-0123", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN321", "CPEN331"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Tim Paine", "name" : "Tim", "major" : "CPSC", "school" : "UBC", "phone" : "567-890-1234", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN411"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Leslie Major", "name" : "Leslie", "major" : "CPSC", "school" : "UBC", "phone" : "678-901-2345", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN421", "CPEN41"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Albert Nosetien", "name" : "Albert", "major" : "IGEN", "school" : "UBC", "phone" : "789-012-3456", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN400A"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Mohammad Ali", "name" : "Mohammad", "major" : "IGEN", "school" : "UBC", "phone" : "890-123-4567", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN331", "CPEN321", "CPEN311"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Ali Zayed", "name" : "Ali", "major" : "MECH", "school" : "UBC", "phone" : "901-234-5678", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN411", "CPEN412" , "CPEN421"] }
######################################################################
POST http://40.117.186.20:3000/profiles/add
Content-Type: application/json

{   "username" : "Justin Jackson", "name" : "Justin", "major" : "MECH", "school" : "UBC", "phone" : "012-345-6789", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN311"] }
######################################################################

######################################################################
#################       SEE USER PROFILE       #######################
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "John Albert" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Mary Monroe" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Aryan Sharma" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "John Watson" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Tim Paine" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Leslie Major" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Albert Nosetien" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Mohammad Ali" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Ali Zayed" }
######################################################################
POST http://40.117.186.20:3000/profiles/search
Content-Type: application/json

{ "username" : "Justin Jackson" }
######################################################################

POST http://40.117.186.20:3000/profiles/update
Content-Type: application/json

{   "username" : "Justin Jackson", "name" : "Jeremy", "major" : "MECH", "school" : "UBC", "phone" : "012-345-6789", "private" : false, "inActivity" : false, "activityID" : "-1", "CourseRegistered" : ["CPEN311"] }
######################################################################
POST http://40.117.186.20:3000/profiles/delete
Content-Type: application/json

{ "username" : "John Albert" }