######################################################################
#################         GET ALL USERS        #######################
######################################################################
GET http://localhost:3000/users/all


######################################################################
#################   POPULATE DB WITH USERS     #######################
######################################################################

POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user1", "password" : "password1"}
##################################################################### 
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user2", "password" : "password2"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user3", "password" : "password3"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user4", "password" : "password4"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user5", "password" : "password5"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user6", "password" : "password6"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user7", "password" : "password7"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user8", "password" : "password8"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user9", "password" : "password9"}
#####################################################################
POST http://localhost:3000/users/register
Content-Type: application/json 

{ "name" : "user10", "password" : "password10"}
#####################################################################

######################################################################
#################      TEST THE API CALLS      #######################
######################################################################
POST http://localhost:3000/users/login
Content-Type: application/json

{ "BadRequest" : "BadRequest"}
######################################################################
POST http://localhost:3000/users/login
Content-Type: application/json

{ "name" : "wrong_username", "password" : "password1"}
######################################################################
POST http://localhost:3000/users/login
Content-Type: application/json

{ "name" : "user1", "password" : "wrong_password"}
######################################################################
POST http://localhost:3000/users/login
Content-Type: application/json

{ "name" : "user1", "password" : "password1"}
######################################################################
