######################################################################
#################      GET ALL ACTIVITIES     ########################
######################################################################
GET http://localhost:3000/localhost:3000/activities/all

######################################################################
##################  POPULATE DB WITH ACTIVITIES  #####################
######################################################################
POST http://localhost:3000/activities/add
Content-Type: application/json

{ "aid" : "a1", "name" : "Cpen221 Exam Prep", "leader" : "user1", "usernames" : ["user1"], "major" : "CPEN", "course" : ["CPEN321", "CPEN331"], "school" : "UBC", "lat" : "49.267941", "long" : "-123.247360", "status" : "1",
    "info" : "We meet regularly everyday on Campus and usually like to study in an open environment. All kinds of questions and doubts regarding CPEN 221 is welcome. We hope to see you soon! :)" }
#####################################################################
POST http://localhost:3000/activities/add
Content-Type: application/json

{ "aid" : "a2", "name" : "Cpen221 Exam Prep", "leader" : "user1", "usernames" : ["user1"], "major" : "CPEN", "course" : ["CPEN321", "CPEN331"], "school" : "UBC", "lat" : "49.267941", "long" : "-123.247360", "status" : "1",
    "info" : "We meet regularly everyday on Campus and usually like to study in an open environment. All kinds of questions and doubts regarding CPEN 221 is welcome. We hope to see you soon! :)" }
#####################################################################
POST http://localhost:3000/activities/add
Content-Type: application/json

{ "aid" : "a3", "name" : "Cpen221 Exam Prep", "leader" : "user1", "usernames" : ["user1"], "major" : "CPEN", "course" : ["CPEN321", "CPEN331"], "school" : "UBC", "lat" : "49.267941", "long" : "-123.247360", "status" : "1",
    "info" : "We meet regularly everyday on Campus and usually like to study in an open environment. All kinds of questions and doubts regarding CPEN 221 is welcome. We hope to see you soon! :)" }
#####################################################################
POST http://localhost:3000/activities/add
Content-Type: application/json

{ "aid" : "a4", "name" : "Cpen221 Exam Prep", "leader" : "user1", "usernames" : ["user1"], "major" : "CPEN", "course" : ["CPEN321", "CPEN331"], "school" : "UBC", "lat" : "49.267941", "long" : "-123.247360", "status" : "1",
    "info" : "We meet regularly everyday on Campus and usually like to study in an open environment. All kinds of questions and doubts regarding CPEN 221 is welcome. We hope to see you soon! :)" }
#####################################################################
POST http://localhost:3000/activities/add
Content-Type: application/json

{ "aid" : "a5", "name" : "Cpen221 Exam Prep", "leader" : "user1", "usernames" : ["user1"], "major" : "CPEN", "course" : ["CPEN321", "CPEN331"], "school" : "UBC", "lat" : "49.267941", "long" : "-123.247360", "status" : "1",
    "info" : "We meet regularly everyday on Campus and usually like to study in an open environment. All kinds of questions and doubts regarding CPEN 221 is welcome. We hope to see you soon! :)" }
#####################################################################