######################################################################
##ACCOUNT DB REQUESTS
######################################################################

### check current users in database
GET http://localhost:3000/users/all

### store a user

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name" : "user1",
    "password" : "password1"
}

### store a user

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name" : "user2",
    "password" : "password2"
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name" : "user3",
    "password" : "password2"
}
### login user (wrong username)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "aKyle",
    "password" : "wrongpas"
}

### login user (wrong password)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "Kyle",
    "password" : "wrongpas"
}

### login user (success)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "user1",
    "password" : "password1"
}

### login user (success)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "Adam",
    "password" : "password1"
}

### login user (success)

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name" : "zyad",
    "password" : "1234"
}

######################################################################
##USER DB REQUESTS
######################################################################

### check current users in database
GET http://localhost:3000/profiles/all

### insert user
POST http://localhost:3000/profiles/add
Content-Type: application/json

{
    "name" : "user1",
    "username" : "user1",
    "major" : "CPEN",
    "CourseRegistered" : [
        "CPEN331", "CPEN321"
    ],
    "school" : "UBC",
    "phone" : "4444444444",
    "private" : false,
    "inActivity" : false,
    "activityID" : "temp"
}

### user joins an activity
POST http://localhost:3000/profiles/join
Content-Type: application/json

{
    "username" : "12",
    "aid" : "test"
}

### insert other user 
POST http://localhost:3000/profiles/add
Content-Type: application/json

{
    "name" : "Jake",
    "username" : "2",
    "major" : "CPEN",
    "CourseRegistered" : [
        "ELEC201", "CPEN311"
    ],
    "school" : "UBC",
    "phone" : "4444445555",
    "private" : false,
    "inActivity" : false,
    "activityID" : "-1"
}

### search user by id
POST http://localhost:3000/profiles/search
Content-Type: application/json

{
    "username" : "12"
}

### search user by id (doesnt exist)
POST http://localhost:3000/profiles/search
Content-Type: application/json

{
    "username" : "2"
}

### update profile with new profile 
POST http://localhost:3000/profiles/update
Content-Type: application/json

{
    "name" : "Jake J",
    "username" : "2",
    "major" : "CPEN",
    "CourseRegistered" : [
        "ELEC201", "CPEN400"
    ],
    "school" : "SFU",
    "phone" : "4442225555",
    "private" : false,
    "inActivity" : false,
    "activityID" : "test"
}

######################################################################
##ACTIVITY DB REQUESTS
######################################################################

### check current activities
GET http://localhost:3000/activities/all

### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "sparklingdangerst",
    "name" : "Cpen321 Project",
    "leader" : "2",
    "usernames" : ["test","aplha"],
    "info" : "Understanding Javascript with TA",
    "major" : "CPEN",
    "course" : ["CPEN321", "CPEN331"],
    "school" : "UBC",
    "lat" : "49.267941",
    "long" : "-123.247360",
    "status" : "1"
}

### insert activity
POST http://localhost:3000/activities/join
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "user" : "Kyle"
}

### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "leader": "user1",
    "usernames" : ["hulk","blackwidow"],
    "info" : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum commodo vulputate condimentum. Mauris congue vulputate dignissim. Sed et nisi erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ",
    "major" : "CPEN",
    "course" : ["CPEN331"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509",
    "status" : "1"
}
### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "differentID",
    "name" : "Cpen331 Project",
    "leader": "hulk",
    "usernames" : ["hulk","blackwidow"],
    "info" : "GOOD ACTIVITY!",
    "major" : "CPEN",
    "course" : ["CPEN331", "CPEN321", "CPEN400"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509",
    "status" : "1"
}
### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "diffID",
    "name" : "Cpen331 Project",
    "leader": "hulk",
    "usernames" : ["hulk","blackwidow"],
    "info" : "okay ACTIVITY!",
    "major" : "CPEN",
    "course" : ["CPEN331","CPEN400","CPEN321","ELEC221"],
    "school" : "UBC",
    "lat" : "50.3112",
    "long" : "-122.213123",
    "status" : "1"
}
### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "difffffid",
    "name" : "Cpen331 Project",
    "leader": "hulk",
    "usernames" : ["hulk","blackwidow"],
    "info" : "bad ACTIVITY!",
    "major" : "CPSC",
    "course" : ["CPEN221"],
    "school" : "UBC",
    "lat" : "49.3112",
    "long" : "-122.43232",
    "status" : "1"
}
### insert activity
POST http://localhost:3000/activities/add
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "leader": "zyad",
    "usernames" : ["hulk","blackwidow"],
    "info" : "far ACTIVITY!",
    "major" : "CPSC",
    "course" : ["CPEN221"],
    "school" : "UBC",
    "lat" : "1",
    "long" : "2",
    "status" : "1"
}


### search activity
POST http://localhost:3000/activities/search
Content-Type: application/json

{
    "aid" : "zyadact"
}

### delete activity
POST http://localhost:3000/activities/delete
Content-Type: application/json

{
    "aid" : "zyadact"
}

### search user by id
POST http://localhost:3000/profiles/search
Content-Type: application/json

{
    "username" : "zyad"
}


### search user by id
POST http://localhost:3000/profiles/leave
Content-Type: application/json

{
    "aid" : "zyadact",
    "username" : "zyad"
}

### search activity
POST http://localhost:3000/activities/joinupdate
Content-Type: application/json

{
    "aid" : "zyadact",
    "username" : "user1"
}

### search activity
POST http://localhost:3000/activities/leaveupdate
Content-Type: application/json

{
    "aid" : "zyadact",
    "username" : "user1"
}

### search activity
POST http://localhost:3000/activities/leaveupdate
Content-Type: application/json

{
    "aid" : "bad",
    "username" : "test"
}


### update users
POST http://localhost:3000/activities/update
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "leader": "hulk",
    "usernames" : ["blackwidow"],
    "info" : "Understanding Life",
    "major" : "CPEN",
    "course" : ["CPEN331"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509",
    "status" : "1"
}

### update users
POST http://localhost:3000/activities/sort
Content-Type: application/json

{
    "user" : {
        "name" : "Kyle",
        "username" : "12",
        "major" : "CPEN",
        "CourseRegistered" : [
            "CPEN331", "CPEN321", "CPEN400", "ELEC221"
        ],
        "school" : "UBC",
        "phone" : "4444444444",
        "private" : false,
        "inActivity" : false,
        "activityID" : -1
    } , 
    "userlat" : "50.3112",
    "userlong" : "-122.213123",
    "maxradius" : 100000,
    "locationweight" : 2,
    "coursesweight" : 3,
    "majorweight" : 1
}

### update users
POST http://localhost:3000/activities/sortnouser
Content-Type: application/json

{
    "username" : "Kyle",
    "userlat" : "50.3112",
    "userlong" : "-122.213123",
    "maxradius" : 100000,
    "locationweight" : 2,
    "coursesweight" : 3,
    "majorweight" : 1
}

### update users
GET http://localhost:3000/notifications/alltokens

### update users
POST http://localhost:3000/notifications/addtoken
Content-Type: application/json

{
    "username" : "Jack",
    "token" : "looolaokda"
}

### update users
POST http://localhost:3000/notifications/send
Content-Type: application/json

{
    "username" : "zyad",
    "title" : "hey",
    "message" : "heyo"
}

### update users
POST http://localhost:3000/notifications/send
Content-Type: application/json

{
    "username" : "john",
    "title" : "hey",
    "message" : "heyo"
}

