### check current activities
GET http://localhost:5000/allactivities

### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "sparklingdangers",
    "name" : "Cpen321 Project",
    "usernames" : ["test","aplha"],
    "info" : "Understanding Javascript with TA",
    "major" : "CPEN",
    "Course" : "CPEN321",
    "school" : "UBC",
    "lat" : "49.267941",
    "long" : "-123.247360"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "Understanding Life",
    "major" : "CPEN",
    "Course" : "CPEN331",
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509"
}


### search activity
POST http://localhost:5000/activitysearch
Content-Type: application/json

{
    "aid" : "ultracheapcow"
}


### update users
POST http://localhost:5000/updateUsers
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "usernames" : ["blackwidow"],
    "info" : "Understanding Life",
    "major" : "CPEN",
    "Course" : "CPEN331",
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509"
}

