### check current activities
GET http://localhost:5000/allactivities

### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "sparklingdangers",
    "name" : "Cpen321 Project",
    "usernames" : ["test","aplha"],
    "info" : "Understanding Javascript with TA",
    "major" : "CPEN",
    "Course" : ["CPEN321", "CPEN331"],
    "school" : "UBC",
    "lat" : "49.267941",
    "long" : "-123.247360"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "Understanding Life",
    "major" : "CPEN",
    "Course" : ["CPEN331"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "differentID",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "GOOD ACTIVITY!",
    "major" : "CPEN",
    "Course" : ["CPEN331", "CPEN321", "CPEN400"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "diffID",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "okay ACTIVITY!",
    "major" : "CPEN",
    "Course" : ["CPEN331","CPEN400","CPEN321","ELEC221"],
    "school" : "UBC",
    "lat" : "50.3112",
    "long" : "-122.213123"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "difffffid",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "bad ACTIVITY!",
    "major" : "CPSC",
    "Course" : ["CPEN221"],
    "school" : "UBC",
    "lat" : "49.3112",
    "long" : "-122.43232"
}
### insert activity
POST http://localhost:5000/addactivity
Content-Type: application/json

{
    "aid" : "diffffffffid",
    "name" : "Cpen331 Project",
    "usernames" : ["hulk","blackwidow"],
    "info" : "far ACTIVITY!",
    "major" : "CPSC",
    "Course" : ["CPEN221"],
    "school" : "UBC",
    "lat" : "1",
    "long" : "2"
}


### search activity
POST http://localhost:5000/activitysearch
Content-Type: application/json

{
    "aid" : "ultracheapcow"
}


### update users
POST http://localhost:5000/updateUsers
Content-Type: application/json

{
    "aid" : "ultracheapcow",
    "name" : "Cpen331 Project",
    "usernames" : ["blackwidow"],
    "info" : "Understanding Life",
    "major" : "CPEN",
    "Course" : ["CPEN331"],
    "school" : "UBC",
    "lat" : "49.104599",
    "long" : "-122.823509"
}

### update users
POST http://localhost:5000/sortactivities
Content-Type: application/json

{
    "user" : {
        "name" : "Kyle",
        "userid" : "12",
        "major" : "CPEN",
        "CourseRegistered" : [
            "CPEN331", "CPEN321", "CPEN400", "ELEC221"
        ],
        "school" : "UBC",
        "phone" : "4444444444",
        "private" : false,
        "inActivity" : false,
        "activityID" : -1
    } , 
    "userlocation" : {
        "lat" : "50.3112",
        "long" : "-122.213123"
    },
    "radius" : 200,
    "locationweight" : 2,
    "coursesweight" : 3,
    "majorweight" : 1
}

